namespace PMS.adminUC.companyop
{
    partial class modifycompany
    {
        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(modifycompany));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.searchbtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuLabel2 = new Bunifu.UI.WinForms.BunifuLabel();
            this.companyidtxt = new Bunifu.UI.WinForms.BunifuTextBox();
            this.resetbtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuButton1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuSeparator1 = new Bunifu.UI.WinForms.BunifuSeparator();
            this.bunifuLabel3 = new Bunifu.UI.WinForms.BunifuLabel();
            this.nametxt = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel4 = new Bunifu.UI.WinForms.BunifuLabel();
            this.phonetxt = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel5 = new Bunifu.UI.WinForms.BunifuLabel();
            this.locationtxt = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel6 = new Bunifu.UI.WinForms.BunifuLabel();
            this.emailtxt = new Bunifu.UI.WinForms.BunifuTextBox();
            this.guna2Elipse1 = new Guna.UI2.WinForms.Guna2Elipse(this.components);
            this.SuspendLayout();
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AllowParentOverrides = false;
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.Font = new System.Drawing.Font("Segoe UI", 26.25F, System.Drawing.FontStyle.Bold);
            this.bunifuLabel1.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(11)))), ((int)(((byte)(22)))), ((int)(((byte)(33)))));
            this.bunifuLabel1.Location = new System.Drawing.Point(108, 74);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(287, 47);
            this.bunifuLabel1.TabIndex = 42;
            this.bunifuLabel1.Text = "Update Company";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // searchbtn
            // 
            this.searchbtn.AllowAnimations = true;
            this.searchbtn.AllowMouseEffects = true;
            this.searchbtn.AllowToggling = true;
            this.searchbtn.AnimationSpeed = 200;
            this.searchbtn.AutoGenerateColors = false;
            this.searchbtn.AutoRoundBorders = false;
            this.searchbtn.AutoSizeLeftIcon = true;
            this.searchbtn.AutoSizeRightIcon = true;
            this.searchbtn.BackColor = System.Drawing.Color.Transparent;
            this.searchbtn.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(17)))), ((int)(((byte)(34)))), ((int)(((byte)(50)))));
            this.searchbtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("searchbtn.BackgroundImage")));
            this.searchbtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.searchbtn.ButtonText = "Search";
            this.searchbtn.ButtonTextMarginLeft = 0;
            this.searchbtn.ColorContrastOnClick = 45;
            this.searchbtn.ColorContrastOnHover = 45;
            this.searchbtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.searchbtn.CustomizableEdges = borderEdges1;
            this.searchbtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.searchbtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.searchbtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.searchbtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.searchbtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Idle;
            this.searchbtn.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.searchbtn.ForeColor = System.Drawing.Color.White;
            this.searchbtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.searchbtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.searchbtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.searchbtn.IconMarginLeft = 11;
            this.searchbtn.IconPadding = 10;
            this.searchbtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.searchbtn.IconRightCursor = System.Windows.Forms.Cursors.Arrow;
            this.searchbtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.searchbtn.IconSize = 25;
            this.searchbtn.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(7)))), ((int)(((byte)(123)))), ((int)(((byte)(50)))));
            this.searchbtn.IdleBorderRadius = 35;
            this.searchbtn.IdleBorderThickness = 1;
            this.searchbtn.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(17)))), ((int)(((byte)(34)))), ((int)(((byte)(50)))));
            this.searchbtn.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("searchbtn.IdleIconLeftImage")));
            this.searchbtn.IdleIconRightImage = null;
            this.searchbtn.IndicateFocus = true;
            this.searchbtn.Location = new System.Drawing.Point(658, 221);
            this.searchbtn.Name = "searchbtn";
            this.searchbtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.searchbtn.OnDisabledState.BorderRadius = 35;
            this.searchbtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.searchbtn.OnDisabledState.BorderThickness = 1;
            this.searchbtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.searchbtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.searchbtn.OnDisabledState.IconLeftImage = null;
            this.searchbtn.OnDisabledState.IconRightImage = null;
            this.searchbtn.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(17)))), ((int)(((byte)(34)))), ((int)(((byte)(50)))));
            this.searchbtn.onHoverState.BorderRadius = 35;
            this.searchbtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.searchbtn.onHoverState.BorderThickness = 1;
            this.searchbtn.onHoverState.FillColor = System.Drawing.Color.White;
            this.searchbtn.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(17)))), ((int)(((byte)(34)))), ((int)(((byte)(50)))));
            this.searchbtn.onHoverState.IconLeftImage = null;
            this.searchbtn.onHoverState.IconRightImage = null;
            this.searchbtn.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(7)))), ((int)(((byte)(123)))), ((int)(((byte)(50)))));
            this.searchbtn.OnIdleState.BorderRadius = 35;
            this.searchbtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.searchbtn.OnIdleState.BorderThickness = 1;
            this.searchbtn.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(17)))), ((int)(((byte)(34)))), ((int)(((byte)(50)))));
            this.searchbtn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.searchbtn.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("searchbtn.OnIdleState.IconLeftImage")));
            this.searchbtn.OnIdleState.IconRightImage = null;
            this.searchbtn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(17)))), ((int)(((byte)(34)))), ((int)(((byte)(50)))));
            this.searchbtn.OnPressedState.BorderRadius = 35;
            this.searchbtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.searchbtn.OnPressedState.BorderThickness = 1;
            this.searchbtn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(7)))), ((int)(((byte)(123)))), ((int)(((byte)(50)))));
            this.searchbtn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.searchbtn.OnPressedState.IconLeftImage = null;
            this.searchbtn.OnPressedState.IconRightImage = null;
            this.searchbtn.Size = new System.Drawing.Size(119, 42);
            this.searchbtn.TabIndex = 90;
            this.searchbtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.searchbtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.searchbtn.TextMarginLeft = 0;
            this.searchbtn.TextPadding = new System.Windows.Forms.Padding(0);
            this.searchbtn.UseDefaultRadiusAndThickness = true;
            this.searchbtn.Click += new System.EventHandler(this.searchbtn_Click);
            // 
            // bunifuLabel2
            // 
            this.bunifuLabel2.AllowParentOverrides = false;
            this.bunifuLabel2.AutoEllipsis = false;
            this.bunifuLabel2.CursorType = null;
            this.bunifuLabel2.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(17)))), ((int)(((byte)(34)))), ((int)(((byte)(50)))));
            this.bunifuLabel2.Location = new System.Drawing.Point(306, 183);
            this.bunifuLabel2.Name = "bunifuLabel2";
            this.bunifuLabel2.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel2.Size = new System.Drawing.Size(92, 21);
            this.bunifuLabel2.TabIndex = 89;
            this.bunifuLabel2.Text = "Company Id";
            this.bunifuLabel2.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel2.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // companyidtxt
            // 
            this.companyidtxt.AcceptsReturn = false;
            this.companyidtxt.AcceptsTab = false;
            this.companyidtxt.AnimationSpeed = 200;
            this.companyidtxt.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.companyidtxt.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.companyidtxt.BackColor = System.Drawing.Color.Transparent;
            this.companyidtxt.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("companyidtxt.BackgroundImage")));
            this.companyidtxt.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(7)))), ((int)(((byte)(123)))), ((int)(((byte)(50)))));
            this.companyidtxt.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.companyidtxt.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(17)))), ((int)(((byte)(34)))), ((int)(((byte)(50)))));
            this.companyidtxt.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(46)))), ((int)(((byte)(61)))), ((int)(((byte)(136)))));
            this.companyidtxt.BorderRadius = 1;
            this.companyidtxt.BorderThickness = 1;
            this.companyidtxt.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.companyidtxt.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.companyidtxt.DefaultFont = new System.Drawing.Font("Segoe UI Semibold", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.companyidtxt.DefaultText = "";
            this.companyidtxt.FillColor = System.Drawing.Color.White;
            this.companyidtxt.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(17)))), ((int)(((byte)(34)))), ((int)(((byte)(50)))));
            this.companyidtxt.HideSelection = true;
            this.companyidtxt.IconLeft = null;
            this.companyidtxt.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.companyidtxt.IconPadding = 10;
            this.companyidtxt.IconRight = null;
            this.companyidtxt.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.companyidtxt.Lines = new string[0];
            this.companyidtxt.Location = new System.Drawing.Point(306, 221);
            this.companyidtxt.MaxLength = 32767;
            this.companyidtxt.MinimumSize = new System.Drawing.Size(1, 1);
            this.companyidtxt.Modified = false;
            this.companyidtxt.Multiline = false;
            this.companyidtxt.Name = "companyidtxt";
            stateProperties1.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(7)))), ((int)(((byte)(123)))), ((int)(((byte)(50)))));
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.companyidtxt.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.companyidtxt.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(17)))), ((int)(((byte)(34)))), ((int)(((byte)(50)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.companyidtxt.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(46)))), ((int)(((byte)(61)))), ((int)(((byte)(136)))));
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(17)))), ((int)(((byte)(34)))), ((int)(((byte)(50)))));
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.companyidtxt.OnIdleState = stateProperties4;
            this.companyidtxt.Padding = new System.Windows.Forms.Padding(3);
            this.companyidtxt.PasswordChar = '\0';
            this.companyidtxt.PlaceholderForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(53)))), ((int)(((byte)(68)))));
            this.companyidtxt.PlaceholderText = "Company Id";
            this.companyidtxt.ReadOnly = false;
            this.companyidtxt.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.companyidtxt.SelectedText = "";
            this.companyidtxt.SelectionLength = 0;
            this.companyidtxt.SelectionStart = 0;
            this.companyidtxt.ShortcutsEnabled = true;
            this.companyidtxt.Size = new System.Drawing.Size(332, 42);
            this.companyidtxt.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.companyidtxt.TabIndex = 88;
            this.companyidtxt.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.companyidtxt.TextMarginBottom = 0;
            this.companyidtxt.TextMarginLeft = 3;
            this.companyidtxt.TextMarginTop = 0;
            this.companyidtxt.TextPlaceholder = "Company Id";
            this.companyidtxt.UseSystemPasswordChar = false;
            this.companyidtxt.WordWrap = true;
            this.companyidtxt.TextChanged += new System.EventHandler(this.companyidtxt_TextChanged);
            // 
            // resetbtn
            // 
            this.resetbtn.AllowAnimations = true;
            this.resetbtn.AllowMouseEffects = true;
            this.resetbtn.AllowToggling = true;
            this.resetbtn.AnimationSpeed = 200;
            this.resetbtn.AutoGenerateColors = false;
            this.resetbtn.AutoRoundBorders = false;
            this.resetbtn.AutoSizeLeftIcon = true;
            this.resetbtn.AutoSizeRightIcon = true;
            this.resetbtn.BackColor = System.Drawing.Color.Transparent;
            this.resetbtn.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(17)))), ((int)(((byte)(34)))), ((int)(((byte)(50)))));
            this.resetbtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("resetbtn.BackgroundImage")));
            this.resetbtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.resetbtn.ButtonText = "Reset";
            this.resetbtn.ButtonTextMarginLeft = 0;
            this.resetbtn.ColorContrastOnClick = 45;
            this.resetbtn.ColorContrastOnHover = 45;
            this.resetbtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.resetbtn.CustomizableEdges = borderEdges2;
            this.resetbtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.resetbtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.resetbtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.resetbtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.resetbtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Idle;
            this.resetbtn.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.resetbtn.ForeColor = System.Drawing.Color.White;
            this.resetbtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.resetbtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.resetbtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.resetbtn.IconMarginLeft = 11;
            this.resetbtn.IconPadding = 10;
            this.resetbtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.resetbtn.IconRightCursor = System.Windows.Forms.Cursors.Arrow;
            this.resetbtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.resetbtn.IconSize = 25;
            this.resetbtn.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(7)))), ((int)(((byte)(123)))), ((int)(((byte)(50)))));
            this.resetbtn.IdleBorderRadius = 35;
            this.resetbtn.IdleBorderThickness = 1;
            this.resetbtn.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(17)))), ((int)(((byte)(34)))), ((int)(((byte)(50)))));
            this.resetbtn.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("resetbtn.IdleIconLeftImage")));
            this.resetbtn.IdleIconRightImage = null;
            this.resetbtn.IndicateFocus = true;
            this.resetbtn.Location = new System.Drawing.Point(613, 564);
            this.resetbtn.Name = "resetbtn";
            this.resetbtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.resetbtn.OnDisabledState.BorderRadius = 35;
            this.resetbtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.resetbtn.OnDisabledState.BorderThickness = 1;
            this.resetbtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.resetbtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.resetbtn.OnDisabledState.IconLeftImage = null;
            this.resetbtn.OnDisabledState.IconRightImage = null;
            this.resetbtn.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(17)))), ((int)(((byte)(34)))), ((int)(((byte)(50)))));
            this.resetbtn.onHoverState.BorderRadius = 35;
            this.resetbtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.resetbtn.onHoverState.BorderThickness = 1;
            this.resetbtn.onHoverState.FillColor = System.Drawing.Color.White;
            this.resetbtn.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(17)))), ((int)(((byte)(34)))), ((int)(((byte)(50)))));
            this.resetbtn.onHoverState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("resource.IconLeftImage")));
            this.resetbtn.onHoverState.IconRightImage = null;
            this.resetbtn.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(7)))), ((int)(((byte)(123)))), ((int)(((byte)(50)))));
            this.resetbtn.OnIdleState.BorderRadius = 35;
            this.resetbtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.resetbtn.OnIdleState.BorderThickness = 1;
            this.resetbtn.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(17)))), ((int)(((byte)(34)))), ((int)(((byte)(50)))));
            this.resetbtn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.resetbtn.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("resetbtn.OnIdleState.IconLeftImage")));
            this.resetbtn.OnIdleState.IconRightImage = null;
            this.resetbtn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(17)))), ((int)(((byte)(34)))), ((int)(((byte)(50)))));
            this.resetbtn.OnPressedState.BorderRadius = 35;
            this.resetbtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.resetbtn.OnPressedState.BorderThickness = 1;
            this.resetbtn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(7)))), ((int)(((byte)(123)))), ((int)(((byte)(50)))));
            this.resetbtn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.resetbtn.OnPressedState.IconLeftImage = null;
            this.resetbtn.OnPressedState.IconRightImage = null;
            this.resetbtn.Size = new System.Drawing.Size(187, 46);
            this.resetbtn.TabIndex = 96;
            this.resetbtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.resetbtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.resetbtn.TextMarginLeft = 0;
            this.resetbtn.TextPadding = new System.Windows.Forms.Padding(0);
            this.resetbtn.UseDefaultRadiusAndThickness = true;
            this.resetbtn.Click += new System.EventHandler(this.resetbtn_Click);
            // 
            // bunifuButton1
            // 
            this.bunifuButton1.AllowAnimations = true;
            this.bunifuButton1.AllowMouseEffects = true;
            this.bunifuButton1.AllowToggling = true;
            this.bunifuButton1.AnimationSpeed = 200;
            this.bunifuButton1.AutoGenerateColors = false;
            this.bunifuButton1.AutoRoundBorders = false;
            this.bunifuButton1.AutoSizeLeftIcon = true;
            this.bunifuButton1.AutoSizeRightIcon = true;
            this.bunifuButton1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton1.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(17)))), ((int)(((byte)(34)))), ((int)(((byte)(50)))));
            this.bunifuButton1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton1.BackgroundImage")));
            this.bunifuButton1.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.ButtonText = "Update";
            this.bunifuButton1.ButtonTextMarginLeft = 0;
            this.bunifuButton1.ColorContrastOnClick = 45;
            this.bunifuButton1.ColorContrastOnHover = 45;
            this.bunifuButton1.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.bunifuButton1.CustomizableEdges = borderEdges3;
            this.bunifuButton1.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton1.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton1.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton1.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton1.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Idle;
            this.bunifuButton1.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuButton1.ForeColor = System.Drawing.Color.White;
            this.bunifuButton1.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton1.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton1.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButton1.IconMarginLeft = 11;
            this.bunifuButton1.IconPadding = 10;
            this.bunifuButton1.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButton1.IconRightCursor = System.Windows.Forms.Cursors.Arrow;
            this.bunifuButton1.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButton1.IconSize = 25;
            this.bunifuButton1.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(7)))), ((int)(((byte)(123)))), ((int)(((byte)(50)))));
            this.bunifuButton1.IdleBorderRadius = 35;
            this.bunifuButton1.IdleBorderThickness = 1;
            this.bunifuButton1.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(17)))), ((int)(((byte)(34)))), ((int)(((byte)(50)))));
            this.bunifuButton1.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton1.IdleIconLeftImage")));
            this.bunifuButton1.IdleIconRightImage = null;
            this.bunifuButton1.IndicateFocus = true;
            this.bunifuButton1.Location = new System.Drawing.Point(253, 564);
            this.bunifuButton1.Name = "bunifuButton1";
            this.bunifuButton1.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton1.OnDisabledState.BorderRadius = 35;
            this.bunifuButton1.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.OnDisabledState.BorderThickness = 1;
            this.bunifuButton1.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton1.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton1.OnDisabledState.IconLeftImage = null;
            this.bunifuButton1.OnDisabledState.IconRightImage = null;
            this.bunifuButton1.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(17)))), ((int)(((byte)(34)))), ((int)(((byte)(50)))));
            this.bunifuButton1.onHoverState.BorderRadius = 35;
            this.bunifuButton1.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.onHoverState.BorderThickness = 1;
            this.bunifuButton1.onHoverState.FillColor = System.Drawing.Color.White;
            this.bunifuButton1.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(17)))), ((int)(((byte)(34)))), ((int)(((byte)(50)))));
            this.bunifuButton1.onHoverState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("resource.IconLeftImage1")));
            this.bunifuButton1.onHoverState.IconRightImage = null;
            this.bunifuButton1.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(7)))), ((int)(((byte)(123)))), ((int)(((byte)(50)))));
            this.bunifuButton1.OnIdleState.BorderRadius = 35;
            this.bunifuButton1.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.OnIdleState.BorderThickness = 1;
            this.bunifuButton1.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(17)))), ((int)(((byte)(34)))), ((int)(((byte)(50)))));
            this.bunifuButton1.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton1.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton1.OnIdleState.IconLeftImage")));
            this.bunifuButton1.OnIdleState.IconRightImage = null;
            this.bunifuButton1.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(17)))), ((int)(((byte)(34)))), ((int)(((byte)(50)))));
            this.bunifuButton1.OnPressedState.BorderRadius = 35;
            this.bunifuButton1.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.OnPressedState.BorderThickness = 1;
            this.bunifuButton1.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(7)))), ((int)(((byte)(123)))), ((int)(((byte)(50)))));
            this.bunifuButton1.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton1.OnPressedState.IconLeftImage = null;
            this.bunifuButton1.OnPressedState.IconRightImage = null;
            this.bunifuButton1.Size = new System.Drawing.Size(187, 46);
            this.bunifuButton1.TabIndex = 95;
            this.bunifuButton1.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButton1.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButton1.TextMarginLeft = 0;
            this.bunifuButton1.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuButton1.UseDefaultRadiusAndThickness = true;
            this.bunifuButton1.Click += new System.EventHandler(this.bunifuButton1_Click);
            // 
            // bunifuSeparator1
            // 
            this.bunifuSeparator1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuSeparator1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuSeparator1.BackgroundImage")));
            this.bunifuSeparator1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuSeparator1.DashCap = Bunifu.UI.WinForms.BunifuSeparator.CapStyles.Flat;
            this.bunifuSeparator1.LineColor = System.Drawing.Color.FromArgb(((int)(((byte)(46)))), ((int)(((byte)(61)))), ((int)(((byte)(136)))));
            this.bunifuSeparator1.LineStyle = Bunifu.UI.WinForms.BunifuSeparator.LineStyles.Solid;
            this.bunifuSeparator1.LineThickness = 3;
            this.bunifuSeparator1.Location = new System.Drawing.Point(0, 286);
            this.bunifuSeparator1.Name = "bunifuSeparator1";
            this.bunifuSeparator1.Orientation = Bunifu.UI.WinForms.BunifuSeparator.LineOrientation.Horizontal;
            this.bunifuSeparator1.Size = new System.Drawing.Size(1020, 14);
            this.bunifuSeparator1.TabIndex = 97;
            // 
            // bunifuLabel3
            // 
            this.bunifuLabel3.AllowParentOverrides = false;
            this.bunifuLabel3.AutoEllipsis = false;
            this.bunifuLabel3.CursorType = null;
            this.bunifuLabel3.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel3.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(17)))), ((int)(((byte)(34)))), ((int)(((byte)(50)))));
            this.bunifuLabel3.Location = new System.Drawing.Point(108, 345);
            this.bunifuLabel3.Name = "bunifuLabel3";
            this.bunifuLabel3.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel3.Size = new System.Drawing.Size(123, 21);
            this.bunifuLabel3.TabIndex = 99;
            this.bunifuLabel3.Text = "Company Name";
            this.bunifuLabel3.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel3.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // nametxt
            // 
            this.nametxt.AcceptsReturn = false;
            this.nametxt.AcceptsTab = false;
            this.nametxt.AnimationSpeed = 200;
            this.nametxt.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.nametxt.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.nametxt.BackColor = System.Drawing.Color.Transparent;
            this.nametxt.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("nametxt.BackgroundImage")));
            this.nametxt.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(7)))), ((int)(((byte)(123)))), ((int)(((byte)(50)))));
            this.nametxt.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.nametxt.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(17)))), ((int)(((byte)(34)))), ((int)(((byte)(50)))));
            this.nametxt.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(46)))), ((int)(((byte)(61)))), ((int)(((byte)(136)))));
            this.nametxt.BorderRadius = 1;
            this.nametxt.BorderThickness = 1;
            this.nametxt.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.nametxt.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.nametxt.DefaultFont = new System.Drawing.Font("Segoe UI Semibold", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.nametxt.DefaultText = "";
            this.nametxt.FillColor = System.Drawing.Color.White;
            this.nametxt.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(17)))), ((int)(((byte)(34)))), ((int)(((byte)(50)))));
            this.nametxt.HideSelection = true;
            this.nametxt.IconLeft = null;
            this.nametxt.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.nametxt.IconPadding = 10;
            this.nametxt.IconRight = null;
            this.nametxt.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.nametxt.Lines = new string[0];
            this.nametxt.Location = new System.Drawing.Point(108, 378);
            this.nametxt.MaxLength = 32767;
            this.nametxt.MinimumSize = new System.Drawing.Size(1, 1);
            this.nametxt.Modified = false;
            this.nametxt.Multiline = false;
            this.nametxt.Name = "nametxt";
            stateProperties5.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(7)))), ((int)(((byte)(123)))), ((int)(((byte)(50)))));
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.nametxt.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.nametxt.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(17)))), ((int)(((byte)(34)))), ((int)(((byte)(50)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.nametxt.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(46)))), ((int)(((byte)(61)))), ((int)(((byte)(136)))));
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(17)))), ((int)(((byte)(34)))), ((int)(((byte)(50)))));
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.nametxt.OnIdleState = stateProperties8;
            this.nametxt.Padding = new System.Windows.Forms.Padding(3);
            this.nametxt.PasswordChar = '\0';
            this.nametxt.PlaceholderForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(53)))), ((int)(((byte)(68)))));
            this.nametxt.PlaceholderText = "Company Name";
            this.nametxt.ReadOnly = false;
            this.nametxt.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.nametxt.SelectedText = "";
            this.nametxt.SelectionLength = 0;
            this.nametxt.SelectionStart = 0;
            this.nametxt.ShortcutsEnabled = true;
            this.nametxt.Size = new System.Drawing.Size(332, 42);
            this.nametxt.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.nametxt.TabIndex = 98;
            this.nametxt.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.nametxt.TextMarginBottom = 0;
            this.nametxt.TextMarginLeft = 3;
            this.nametxt.TextMarginTop = 0;
            this.nametxt.TextPlaceholder = "Company Name";
            this.nametxt.UseSystemPasswordChar = false;
            this.nametxt.WordWrap = true;
            // 
            // bunifuLabel4
            // 
            this.bunifuLabel4.AllowParentOverrides = false;
            this.bunifuLabel4.AutoEllipsis = false;
            this.bunifuLabel4.CursorType = null;
            this.bunifuLabel4.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel4.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(17)))), ((int)(((byte)(34)))), ((int)(((byte)(50)))));
            this.bunifuLabel4.Location = new System.Drawing.Point(613, 345);
            this.bunifuLabel4.Name = "bunifuLabel4";
            this.bunifuLabel4.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel4.Size = new System.Drawing.Size(116, 21);
            this.bunifuLabel4.TabIndex = 101;
            this.bunifuLabel4.Text = "Phone Number";
            this.bunifuLabel4.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel4.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // phonetxt
            // 
            this.phonetxt.AcceptsReturn = false;
            this.phonetxt.AcceptsTab = false;
            this.phonetxt.AnimationSpeed = 200;
            this.phonetxt.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.phonetxt.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.phonetxt.BackColor = System.Drawing.Color.Transparent;
            this.phonetxt.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("phonetxt.BackgroundImage")));
            this.phonetxt.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(7)))), ((int)(((byte)(123)))), ((int)(((byte)(50)))));
            this.phonetxt.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.phonetxt.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(17)))), ((int)(((byte)(34)))), ((int)(((byte)(50)))));
            this.phonetxt.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(46)))), ((int)(((byte)(61)))), ((int)(((byte)(136)))));
            this.phonetxt.BorderRadius = 1;
            this.phonetxt.BorderThickness = 1;
            this.phonetxt.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.phonetxt.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.phonetxt.DefaultFont = new System.Drawing.Font("Segoe UI Semibold", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.phonetxt.DefaultText = "";
            this.phonetxt.FillColor = System.Drawing.Color.White;
            this.phonetxt.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(17)))), ((int)(((byte)(34)))), ((int)(((byte)(50)))));
            this.phonetxt.HideSelection = true;
            this.phonetxt.IconLeft = null;
            this.phonetxt.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.phonetxt.IconPadding = 10;
            this.phonetxt.IconRight = null;
            this.phonetxt.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.phonetxt.Lines = new string[0];
            this.phonetxt.Location = new System.Drawing.Point(613, 378);
            this.phonetxt.MaxLength = 32767;
            this.phonetxt.MinimumSize = new System.Drawing.Size(1, 1);
            this.phonetxt.Modified = false;
            this.phonetxt.Multiline = false;
            this.phonetxt.Name = "phonetxt";
            stateProperties9.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(7)))), ((int)(((byte)(123)))), ((int)(((byte)(50)))));
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.phonetxt.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.phonetxt.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(17)))), ((int)(((byte)(34)))), ((int)(((byte)(50)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.phonetxt.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(46)))), ((int)(((byte)(61)))), ((int)(((byte)(136)))));
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(17)))), ((int)(((byte)(34)))), ((int)(((byte)(50)))));
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.phonetxt.OnIdleState = stateProperties12;
            this.phonetxt.Padding = new System.Windows.Forms.Padding(3);
            this.phonetxt.PasswordChar = '\0';
            this.phonetxt.PlaceholderForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(53)))), ((int)(((byte)(68)))));
            this.phonetxt.PlaceholderText = "Phone Number";
            this.phonetxt.ReadOnly = false;
            this.phonetxt.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.phonetxt.SelectedText = "";
            this.phonetxt.SelectionLength = 0;
            this.phonetxt.SelectionStart = 0;
            this.phonetxt.ShortcutsEnabled = true;
            this.phonetxt.Size = new System.Drawing.Size(332, 42);
            this.phonetxt.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.phonetxt.TabIndex = 100;
            this.phonetxt.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.phonetxt.TextMarginBottom = 0;
            this.phonetxt.TextMarginLeft = 3;
            this.phonetxt.TextMarginTop = 0;
            this.phonetxt.TextPlaceholder = "Phone Number";
            this.phonetxt.UseSystemPasswordChar = false;
            this.phonetxt.WordWrap = true;
            // 
            // bunifuLabel5
            // 
            this.bunifuLabel5.AllowParentOverrides = false;
            this.bunifuLabel5.AutoEllipsis = false;
            this.bunifuLabel5.CursorType = null;
            this.bunifuLabel5.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel5.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(17)))), ((int)(((byte)(34)))), ((int)(((byte)(50)))));
            this.bunifuLabel5.Location = new System.Drawing.Point(108, 447);
            this.bunifuLabel5.Name = "bunifuLabel5";
            this.bunifuLabel5.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel5.Size = new System.Drawing.Size(143, 21);
            this.bunifuLabel5.TabIndex = 103;
            this.bunifuLabel5.Text = "Company Location";
            this.bunifuLabel5.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel5.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // locationtxt
            // 
            this.locationtxt.AcceptsReturn = false;
            this.locationtxt.AcceptsTab = false;
            this.locationtxt.AnimationSpeed = 200;
            this.locationtxt.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.locationtxt.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.locationtxt.BackColor = System.Drawing.Color.Transparent;
            this.locationtxt.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("locationtxt.BackgroundImage")));
            this.locationtxt.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(7)))), ((int)(((byte)(123)))), ((int)(((byte)(50)))));
            this.locationtxt.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.locationtxt.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(17)))), ((int)(((byte)(34)))), ((int)(((byte)(50)))));
            this.locationtxt.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(46)))), ((int)(((byte)(61)))), ((int)(((byte)(136)))));
            this.locationtxt.BorderRadius = 1;
            this.locationtxt.BorderThickness = 1;
            this.locationtxt.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.locationtxt.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.locationtxt.DefaultFont = new System.Drawing.Font("Segoe UI Semibold", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.locationtxt.DefaultText = "";
            this.locationtxt.FillColor = System.Drawing.Color.White;
            this.locationtxt.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(17)))), ((int)(((byte)(34)))), ((int)(((byte)(50)))));
            this.locationtxt.HideSelection = true;
            this.locationtxt.IconLeft = null;
            this.locationtxt.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.locationtxt.IconPadding = 10;
            this.locationtxt.IconRight = null;
            this.locationtxt.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.locationtxt.Lines = new string[0];
            this.locationtxt.Location = new System.Drawing.Point(108, 480);
            this.locationtxt.MaxLength = 32767;
            this.locationtxt.MinimumSize = new System.Drawing.Size(1, 1);
            this.locationtxt.Modified = false;
            this.locationtxt.Multiline = false;
            this.locationtxt.Name = "locationtxt";
            stateProperties13.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(7)))), ((int)(((byte)(123)))), ((int)(((byte)(50)))));
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.locationtxt.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.locationtxt.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(17)))), ((int)(((byte)(34)))), ((int)(((byte)(50)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.locationtxt.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(46)))), ((int)(((byte)(61)))), ((int)(((byte)(136)))));
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(17)))), ((int)(((byte)(34)))), ((int)(((byte)(50)))));
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.locationtxt.OnIdleState = stateProperties16;
            this.locationtxt.Padding = new System.Windows.Forms.Padding(3);
            this.locationtxt.PasswordChar = '\0';
            this.locationtxt.PlaceholderForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(53)))), ((int)(((byte)(68)))));
            this.locationtxt.PlaceholderText = "Company Location";
            this.locationtxt.ReadOnly = false;
            this.locationtxt.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.locationtxt.SelectedText = "";
            this.locationtxt.SelectionLength = 0;
            this.locationtxt.SelectionStart = 0;
            this.locationtxt.ShortcutsEnabled = true;
            this.locationtxt.Size = new System.Drawing.Size(332, 42);
            this.locationtxt.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.locationtxt.TabIndex = 102;
            this.locationtxt.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.locationtxt.TextMarginBottom = 0;
            this.locationtxt.TextMarginLeft = 3;
            this.locationtxt.TextMarginTop = 0;
            this.locationtxt.TextPlaceholder = "Company Location";
            this.locationtxt.UseSystemPasswordChar = false;
            this.locationtxt.WordWrap = true;
            // 
            // bunifuLabel6
            // 
            this.bunifuLabel6.AllowParentOverrides = false;
            this.bunifuLabel6.AutoEllipsis = false;
            this.bunifuLabel6.CursorType = null;
            this.bunifuLabel6.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(17)))), ((int)(((byte)(34)))), ((int)(((byte)(50)))));
            this.bunifuLabel6.Location = new System.Drawing.Point(613, 447);
            this.bunifuLabel6.Name = "bunifuLabel6";
            this.bunifuLabel6.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel6.Size = new System.Drawing.Size(107, 21);
            this.bunifuLabel6.TabIndex = 105;
            this.bunifuLabel6.Text = "Email Address";
            this.bunifuLabel6.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel6.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // emailtxt
            // 
            this.emailtxt.AcceptsReturn = false;
            this.emailtxt.AcceptsTab = false;
            this.emailtxt.AnimationSpeed = 200;
            this.emailtxt.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.emailtxt.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.emailtxt.BackColor = System.Drawing.Color.Transparent;
            this.emailtxt.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("emailtxt.BackgroundImage")));
            this.emailtxt.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(7)))), ((int)(((byte)(123)))), ((int)(((byte)(50)))));
            this.emailtxt.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.emailtxt.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(17)))), ((int)(((byte)(34)))), ((int)(((byte)(50)))));
            this.emailtxt.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(46)))), ((int)(((byte)(61)))), ((int)(((byte)(136)))));
            this.emailtxt.BorderRadius = 1;
            this.emailtxt.BorderThickness = 1;
            this.emailtxt.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.emailtxt.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.emailtxt.DefaultFont = new System.Drawing.Font("Segoe UI Semibold", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.emailtxt.DefaultText = "";
            this.emailtxt.FillColor = System.Drawing.Color.White;
            this.emailtxt.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(17)))), ((int)(((byte)(34)))), ((int)(((byte)(50)))));
            this.emailtxt.HideSelection = true;
            this.emailtxt.IconLeft = null;
            this.emailtxt.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.emailtxt.IconPadding = 10;
            this.emailtxt.IconRight = null;
            this.emailtxt.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.emailtxt.Lines = new string[0];
            this.emailtxt.Location = new System.Drawing.Point(613, 480);
            this.emailtxt.MaxLength = 32767;
            this.emailtxt.MinimumSize = new System.Drawing.Size(1, 1);
            this.emailtxt.Modified = false;
            this.emailtxt.Multiline = false;
            this.emailtxt.Name = "emailtxt";
            stateProperties17.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(7)))), ((int)(((byte)(123)))), ((int)(((byte)(50)))));
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.emailtxt.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.emailtxt.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(17)))), ((int)(((byte)(34)))), ((int)(((byte)(50)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.emailtxt.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(46)))), ((int)(((byte)(61)))), ((int)(((byte)(136)))));
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(17)))), ((int)(((byte)(34)))), ((int)(((byte)(50)))));
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.emailtxt.OnIdleState = stateProperties20;
            this.emailtxt.Padding = new System.Windows.Forms.Padding(3);
            this.emailtxt.PasswordChar = '\0';
            this.emailtxt.PlaceholderForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(53)))), ((int)(((byte)(68)))));
            this.emailtxt.PlaceholderText = "Email Address";
            this.emailtxt.ReadOnly = false;
            this.emailtxt.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.emailtxt.SelectedText = "";
            this.emailtxt.SelectionLength = 0;
            this.emailtxt.SelectionStart = 0;
            this.emailtxt.ShortcutsEnabled = true;
            this.emailtxt.Size = new System.Drawing.Size(332, 42);
            this.emailtxt.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.emailtxt.TabIndex = 104;
            this.emailtxt.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.emailtxt.TextMarginBottom = 0;
            this.emailtxt.TextMarginLeft = 3;
            this.emailtxt.TextMarginTop = 0;
            this.emailtxt.TextPlaceholder = "Email Address";
            this.emailtxt.UseSystemPasswordChar = false;
            this.emailtxt.WordWrap = true;
            // 
            // guna2Elipse1
            // 
            this.guna2Elipse1.TargetControl = this;
            // 
            // modifycompany
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.Controls.Add(this.bunifuLabel6);
            this.Controls.Add(this.emailtxt);
            this.Controls.Add(this.bunifuLabel5);
            this.Controls.Add(this.locationtxt);
            this.Controls.Add(this.bunifuLabel4);
            this.Controls.Add(this.phonetxt);
            this.Controls.Add(this.bunifuLabel3);
            this.Controls.Add(this.nametxt);
            this.Controls.Add(this.bunifuSeparator1);
            this.Controls.Add(this.resetbtn);
            this.Controls.Add(this.bunifuButton1);
            this.Controls.Add(this.searchbtn);
            this.Controls.Add(this.bunifuLabel2);
            this.Controls.Add(this.companyidtxt);
            this.Controls.Add(this.bunifuLabel1);
            this.Name = "modifycompany";
            this.Size = new System.Drawing.Size(1020, 744);
            this.Load += new System.EventHandler(this.modifycompany_Load);
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton searchbtn;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel2;
        private Bunifu.UI.WinForms.BunifuTextBox companyidtxt;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton resetbtn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButton1;
        private Bunifu.UI.WinForms.BunifuSeparator bunifuSeparator1;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel3;
        private Bunifu.UI.WinForms.BunifuTextBox nametxt;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel4;
        private Bunifu.UI.WinForms.BunifuTextBox phonetxt;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel5;
        private Bunifu.UI.WinForms.BunifuTextBox locationtxt;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel6;
        private Bunifu.UI.WinForms.BunifuTextBox emailtxt;
        private Guna.UI2.WinForms.Guna2Elipse guna2Elipse1;
    }
}
